### ISSUE TITLE
Receiving the daily quest while in game causes the game to become blurry

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#1076]
Current mitigation steps: 
\- You can start a new game to fix it. 
\- Also going to the pack opening screen and back to the main menu will fix it.

---

Reports from PC and Mobile

https://us.battle.net/forums/en/hearthstone/topic/20770136832

https://www.reddit.com/r/hearthstone/comments/a2yqjx/new_hardcore_mode_is_called_blur_mode_d/

![image](https://user-images.githubusercontent.com/22508641/49832427-9dc09100-fd64-11e8-8f96-dc7722594497.png)

https://www.reddit.com/r/hearthstone/comments/a5bcom/bug_if_youre_online_when_you_get_your_quest_and/

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/a69yv3/glitch_with_new_solo_content/

> So to summarise i was playing the new solo stuff when it turned 11 during my game (UK player) so it gave us our new daily quest. This causes the quest to appear and vanish and left the game all blurred like this. It stayed like this after going into a different game or into a collection. Fixed on restart just a little annoying bug.

**Comment by riQQ** [comment]
Can confirm this happening in 13.0.3.28242

**Comment by troggnostupidhs** [comment]
![hearthstone screenshot 12-15-18 03 09 57](https://user-images.githubusercontent.com/22508641/50040724-151d4b80-0017-11e9-994d-5f8ff2057eaa.png)

**Comment by troggnostupidhs** [comment]
https://www.youtube.com/watch?v=wtLsB_OcNn4&t=619

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20770737226#post-2

> Thanks for the report! The next upcoming update should have the screen blur addressed.

**Comment by Jetz72** [comment]
It was not addressed in the latest update.

![hearthstone screenshot 02-16-19 03 14 34](https://user-images.githubusercontent.com/8607832/52896687-2f9bae80-3199-11e9-935b-1441e9ece439.png)

**Comment by troggnostupidhs** [comment]
Also happens when getting the beginning quests on a new account.

![hearthstone screenshot 02-23-19 16 00 50](https://user-images.githubusercontent.com/22508641/53291620-3e2f2a80-3784-11e9-88fc-b0c8316d9285.png)

**Comment by Doppeey** [comment]
same happening to me, also with beginning quests

**Comment by mandaputtra** [comment]
Same happening to me -_-

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/b1llih/this_happens_every_time_i_finish_a_game_and_a_new/

**Comment by mandaputtra** [comment]
Seems like it fixed by now. thanks

**Comment by riQQ** [comment]
Not fixed for me:
![grafik](https://user-images.githubusercontent.com/3404787/55118492-cc356280-50ee-11e9-9634-3cff4c9eb446.png)

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/bbbawh/bug_hearthstone_permanently_blurry_new_bug/

**Comment by riQQ** [comment]
Can confirm it's still happening

**Comment by exo-pla-net** [comment]
Still happening.

**Comment by troggnostupidhs** [comment]
https://youtu.be/VdKWG3gbef0?t=852

**Comment by troggnostupidhs** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/screen-blurry-after-opening-packs-quest-pop-up-or-match-completion/3422/11

> Thanks everyone! This is a known issue that we’re currently tracking and working on a resolution for.
> 
> The workaround to get past this, is to start a new match or restart the game client if the blurry screen comes up.

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/22992997

> Fixed an issue which would occasionally leave the screen blurry after finishing a game under certain circumstances.
