### ISSUE TITLE
Minions copied by Faceless Manipulator will have their play sound missing if you return them to your hand and replay them

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#130]
If you use Faceless Manipulator on one of the minions, return the new minion back to your hand and then replay the minion again, his play sound will be missing.
* https://www.youtube.com/watch?v=SsaTDv1hhgE&t=54s

**Comment by culinko** [comment]
Similar thing happens if you damage Grim Patron and return the new one back to your hand and then replay it again. I just tested it myself, but don't have any video proof.

**Comment by jleclanche** [comment]
Can this be generalized to "Summoned minions will have their play sound missing"?

**Comment by culinko** [comment]
But minions like Boar from Razorfen Hunter have their sound present. Same goes from minions summoned by Deathlord.

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/4gsbec/evolved_minions_do_not_behave_exactly_like/ 

Also happens with minions from evolution

**Comment by Patashu** [comment]
Confirmed in 5.0.0.13

https://www.reddit.com/r/hearthstone/comments/4m89vi/sap_bug/

**Comment by Patashu** [comment]
https://www.youtube.com/watch?v=NiRXk1wcvUo&t=7m39s

Looks like Anub'arak created by N'Zoth, died/bounced to hand and replayed lacks the SFX too.

**Comment by culinko** [comment]
Cleaned the issue a bit. Also I found out that you don't need to return the minion to your hand to observe the bug at all. This bug happens right after you play any of the cards mentioned in the description. For example if you play Master of Evolution or Recombobulator, the minion's entrance sound is played right after the transformation finishes, but not after Faceless Manipulator's transformation. Same thing happens with cards that summon multiple minions. For example after Kel'Thuzad revives your board, all of the entrance sounds of your minions will be played, but that does not happen with N'Zoth or Evolve.

**Comment by Patashu** [comment]
https://www.youtube.com/watch?v=NAzEp8vBaco
At 11:00 kibler plays tirion entombed from nzoth and the sfx is missing.

**Comment by Patashu** [comment]
Confirmed in 7.0?

https://us.battle.net/forums/en/hearthstone/topic/20752605516?page=1#post-2

**Comment by culinko** [comment]
Faceless has been fixed in the meantime, but Grim Patron, Evolve and Herald Volazj are still bugged in 7.1 (haven't tested N'Zoth).

**Comment by Bert-Proesmans** [comment]
Still an issue in 9.0 for evolved and then vanished minions.
```
there is still a bug with play sounds when minions got evolved, vanished and replayed. I noticed the missing sounds in this game: https://hsreplay.net/replay/aAhAXJ7fetzW7q4P7f5We7#turn=13a -> all minions in my opponents hand, except doppleganger, were evolved and vanished. when my opponent played them their sounds didn't play.
```

**Comment by troggnostupidhs** [comment]
Still happens with Vanish

https://www.reddit.com/r/hearthstone/comments/7wufwr/hearthstone_bug_with_vanish_and_call_to_arms/

> The problem is that if the minions get vanished and you replay them from hand, they won't perform their voice line.
