### ISSUE TITLE
You can hear sound effects when you move your mouse inside non-Hearthstone window if you have enabled sound in background

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#209]
If you enable the "Sound in Background" option and switch to other programs such that their windows are overlaid over the Hearthstone window in the background, when you move your mouse inside the non-Hearthstone window over the locations, such as your cards at mulligan or the history sidebar tile, you can still hear the sound effects as though the active non-Hearthstone program window is not present.
- ~~http://us.battle.net/hearthstone/en/forum/topic/12033553477~~
- ~~https://www.youtube.com/watch?v=WDWvCeESM84~~

**The sound of the UI buttons was fixed in Patch 4.2 or 4.3, however other sound effects, such as your cards at mulligan or the history sidebar tile still make sound effects as if Hearthstone window wasn't in background.**

**Comment by culinko** [comment]
Fixed either in 4.2 or 4.3.

**Comment by culinko** [comment]
You can hear UI buttons again in 5.2.

**Comment by troggnostupidhs** [comment]
Possibly fixed

https://playhearthstone.com/en-us/blog/21098848

> Hearthstone’s engine has been updated to Unity version 5.6.

**Comment by culinko** [comment]
You can no longer hear the UI buttons, but you can still hear the sound when hovering over your cards at mulligan or over history sidebar.

**Comment by troggnostupidhs** [comment]
^ I'm not sure I tested that correctly, I might not have had background sound off

**Comment by troggnostupidhs** [comment]
This should be fixed.

**Comment by culinko** [comment]
I tested this just now and it's still present. I am able to hear sounds when I hover over my cards at mulligan and over the history sidebar entries. I'm running hs in windowed mode and tested it with regular Notepad in front of the hs window.
