### ISSUE TITLE
In-place Steal effects result in target destruction on a full board

### ISSUE THREAD

**Issue by PattuX** [HearthSim/hs-bugs#259]
If you cast a Shadow Madness on an enemy minion while having 6 minions on the board, your first played Djinni of Zephyrs will die and all remaining Djinnis will gain charge. 

* https://www.youtube.com/watch?v=a0ueqgdh_NA

In addition, if you use Cabal Shadow Priest with Brann Bronzebeard in play, and stealing the enemy minion makes your board full, the second Cabal Battlecry will destroy the stolen minion, because it sees that the destination is full and counts itself.

* https://www.youtube.com/watch?v=eph9nuMSN40

This is likely a bug, because a similar interaction occurred if you bounced a minion from your hand to your hand while your hand was full (such as by destroying your Anub'arak with a 9/10 card hand and Baron Rivendare in play), and this interaction was changed to not discard the double bounced minion from your hand.

Acknowledged as a bug here:

* https://twitter.com/hijackeerr/status/679272356687314944

**Comment by jleclanche** [comment]
Yeah, this is because of the zone size check in Steal. it could be reproduced with mind control before djinni, I thought we had a bug open for it.

**Comment by PattuX** [comment]
You mean #174 ?
I don't feel like that is the bug here tho...

**Comment by jleclanche** [comment]
No, it's a different one. Basically, when a steal effect happens in the play zone, it checks if the size of the target zone >= 7. But if source zone == target zone, that check obviously shouldn't happen.

**Comment by Patashu** [comment]
Should it also not create summoning sickness (in the case of in-place Mind Control)?

**Comment by jleclanche** [comment]
Doesn't it?

**Comment by Xinhuan** [comment]
The in-place steal effect @jleclanche cited is from this video last year by Bubchacha:

https://www.youtube.com/watch?v=rc7oejbhdUA

It is mentioned tangentially in #159 where it affects in-place "return to hand", but otherwise no existing issue created for in-place steal effects in the play zone.

**Comment by PattuX** [comment]
Despite the fact that the Shadow Madness shouldn't kill minions in those cases, I'm still pretty sure Shadow Madness shouldn't be cast on the Djinnis at all...

**Comment by jleclanche** [comment]
I think the main problem is that until now, Steal effects could never be cast on friendly minions so we seldom got to see what happened with them in such situations. So this needs Blizzard's word on it, but I'm guessing it's pretty clearly a design issue.

Pah, besides, if Djinni didn't have a timing inconsistent with its card text this wouldn't even be a problem...

**Comment by PattuX** [comment]
It was a problem before. Just look at Sylvanas shenanigans in the several yt links e.g.

**Comment by jleclanche** [comment]
I know, yes, but it was nearly impossible for it to happen in a real game. With this, we might see it addressed, as it's not an unlikely issue to come up in a game.

**Comment by culinko** [comment]
https://www.reddit.com/r/hearthstone/comments/3tgy3q/brann_cabal/

**Comment by PattuX** [comment]
Could someone test whether this also happens, when you try to "return" your own minion to you own board with Shadow Madness?

**Comment by culinko** [comment]
It's the same interaction as can be seen in the video that Xinhuan linked, just for the opposing player.

**Comment by Patashu** [comment]
FYI: Double-bouncing into a 9/10 card hand (Baron Rivendare + Anub'arak) no longer discards the card. Tested in Patch 4.0. So we can only see this interaction with minions now.

**Comment by Patashu** [comment]
added https://www.youtube.com/watch?v=eph9nuMSN40

**Comment by PattuX** [comment]
Confirmed with Brann + Cabal in 4.1

**Comment by Patashu** [comment]
Confirmed as a bug by Ben Brode on twitter here:

https://twitter.com/hijackeerr/status/679272356687314944

**Comment by Patashu** [comment]
Can this please be tested in 4.2? It's probably fixed, and if it is, I need to update the Advanced rulebook appropriately.

**Comment by culinko** [comment]
Tested all 3 interactions, fixed in 4.2.

**Comment by Patashu** [comment]
https://github.com/HearthSim/hs-bugs/issues/259

Interesting, this bug is back in 5.0.

**Comment by Patashu** [comment]
It's possible this bug got hotfixed today.

**Comment by culinko** [comment]
Yes, can confirm it's been fixed.
