### ISSUE TITLE
The state of weapons is not updated between Battlecries doubled by Brann Bronzebeard

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#303]
If you play Brann Bronzebeard and use Harrison Jones on an enemy Death's Bite, the enemy Death's Bite Deathrattle does not resolve until after both Battlecries finish. This proves that Hearthstone does not check for weapon destruction between the two Battlecries.

* https://www.youtube.com/watch?v=U3Pv4jhJ9dk

If you play Brann Bronzebeard and play Blingtron 5000 and Blingtron 5000 gives a Death's Bite to one or both players on the first Battlecry, the Death's Bite Deathrattle will not activate. This proves that Hearthstone does not check for weapon creation between the two Battlecries.

* https://www.reddit.com/r/hearthstone/comments/3va5w7/unusual_brann_blingtron_interaction/

* 
![image](https://cloud.githubusercontent.com/assets/666597/11576192/12bd6a62-9a69-11e5-8da4-29bd239b2242.png)

**Comment by Patashu** [comment]
Related to https://github.com/HearthSim/hs-bugs/issues/25 . So long as https://github.com/HearthSim/hs-bugs/issues/25 exists, we expect weapon deathrattles to run between the two Battlecries.

**Comment by Patashu** [comment]
http://imgur.com/a/KAeLr

https://gist.github.com/culinko/9c5b584b365f7c934d72

Just putting this here while I think of what to do with it - if you play Brann + Dreadsail Corsair while your opponent has a 1 Durability Weapon, it goes to -1 Durability before breaking. This is probably working as intended under any model, but it's a really cool effect

**Comment by Patashu** [comment]
Two interesting interactions:

1) Cursed Blade's 'double damage' effect is in effect the moment Cursed Blade enters play https://www.youtube.com/watch?v=kCiQ2lb1TSM

2) Death's Bite Deathrattle when equipped over seems to happen at a timing about equal to the following Summon Resolution Step https://www.youtube.com/watch?v=bPPVVr3Ohdc

**Comment by Patashu** [comment]
Confirmed in 5.0

http://us.battle.net/hearthstone/en/forum/topic/20743684572

**Comment by Xinhuan** [comment]
Confirmed by blue (IksarHS) as a bug here: https://www.reddit.com/r/hearthstone/comments/4i5ksa/warrior_loses_to_sjow_because_of_a_bug_involving/d2vbsub

**Comment by jleclanche** [comment]
IksarHS update from today:

> Strange, thought this was fixed. Will check on Monday to see if there were complications. Thanks for letting us know.

**Comment by Kybxd** [comment]
This still happens in recent patch. (retested but didn't record the video)

Besides, I have done several tests about 'playing a weapon', now it seems to work like this:

1.On Play Phase: First your new weapon enters play. All triggers on playing a card Queue and resolve here, such as Questing Adventurer, Fel Reaver and Illidan Stormrage.
2.Equipping Phase: The Battlecry of your new weapon (if any) is resolved. Then Buccaneer triggers. Finally your old weapon is destroyed and removed from play. The Deathrattle of your old weapon (if any) is resolved.

* Your old weapon isn't removed immediately your new weapon enters play, leading to the following interactions:(https://youtu.be/Z1Ap-yb4sY4)(https://youtu.be/IhHiQyc0mZg) These are also evidences for your new weapon entering play even before Illidan.
* About Buccaneer's timings:(https://youtu.be/mo3IIGAjnds) If you only equip (rather than play) a weapon, it just triggers after you equip it. It's very similar to Knife Juggler.
* Evidences for your old weapon not leaving play until a very late timing:(https://youtu.be/CT1wKYvFzaw) (https://youtu.be/kXZ0vfKE5xA)

**Comment by culinko** [comment]
> If you play Brann Bronzebeard and play Blingtron 3000 and Blingtron 3000 gives a Death's Bite to one or both players on the first Battlecry, the Death's Bite Deathrattle will not activate. This proves that Hearthstone does not check for weapon creation between the two Battlecries.

This is likely fixed in Patch 10.0 according to patch notes. All of the things mentioned here should be re-tested.

**Comment by troggnostupidhs** [comment]
Brann + Harrison on Death's Bite. Drew 4 cards, but the 1 damage is only dealt once after drawing all cards (it seems). Looks like it still happens. 

![img000](https://user-images.githubusercontent.com/22508641/47956926-8206e580-df83-11e8-8fe9-dc6246993390.png)
![img001](https://user-images.githubusercontent.com/22508641/47956927-8206e580-df83-11e8-91a1-e9e96bdf97b2.png)
![img002](https://user-images.githubusercontent.com/22508641/47956928-8206e580-df83-11e8-9491-f06f762a5edf.png)
![img003](https://user-images.githubusercontent.com/22508641/47956929-829f7c00-df83-11e8-96e2-d8b86168990b.png)
![img004](https://user-images.githubusercontent.com/22508641/47956930-829f7c00-df83-11e8-816e-29efa26211ba.png)

Deck
AAEBAQcCkAeFFw6zAb8B+wGdAoUD/gO5Bv8HjQ63bIKtAuLKAvbPAqbwAgA=

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/22596834/hearthstone-update-november-5-pre-purchase-rastakhan-s-rumble

> Deathrattles on replaced weapons now trigger at the same time as minions in play are destroyed, so Powermace will no longer “save” minions destroyed by Blood Razor’s Battlecry.
