### ISSUE TITLE
Feign Death triggers death event for added deathrattles (Ancestral Spirit)

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#36]
If you cast Feign Death and have on the field a friendly minion with both a Deathrattle and an on-Death Triggered effect, the on-death triggered effect will go off once for its own 'feigned death'. It will not go off for other minions with Deathrattles. To do this, you have to play a minion such as Scavenging Hyena or Flesheating Ghoul and add a Deathrattle such as Ancestral Spirit or the Brawl effect of The Masked Ball. This is a bug because Feign Death is meant to only trigger Deathrattles, not on-death Triggers, and does not, for example, count as a death to Kel'Thuzad either.

[[Hearthstone Science] Feign Death vs Added Deathrattles Bug](https://www.youtube.com/watch?v=W52xmRRgvdU)

**Comment by jleclanche** [comment]
Fixed in 4.0.0.10833

**Comment by culinko** [comment]
Still happens in 4.0.0.10833. I just tested it with Flesheating Ghoul, Explorer's Hat and Feign Death. I will post log shorty.

**Comment by Xinhuan** [comment]
Reported to still be happening in 4.1 here:
https://www.reddit.com/r/hearthstone/comments/3wf4yo/well_this_is_the_weirdest_combo_i_have_seen/

**Comment by PattuX** [comment]
Not happening with Princess Huhuran (although the target triggers visually):

* https://www.youtube.com/watch?v=JNf-U0QiaFI

**Comment by Patashu** [comment]
Confirmed in 7.0:

http://us.battle.net/forums/en/hearthstone/topic/20752277794

**Comment by VoidMayonnaise** [comment]
https://youtu.be/3FOtyd6Q16g
Confirmed in 8.2.

**Comment by troggnostupidhs** [comment]
Still happnens

![img002](https://user-images.githubusercontent.com/22508641/32665870-abe4f206-c603-11e7-8859-ab536c1cfc4b.png)
![img003](https://user-images.githubusercontent.com/22508641/32665871-abf148a8-c603-11e7-9e1b-6cd16a604c03.png)
![img004](https://user-images.githubusercontent.com/22508641/32665872-ac02ed06-c603-11e7-8a65-a2f1b9835a9c.png)

**Comment by riQQ** [comment]
Might be fixed in 10.0.0.22611
> Granting a Deathrattle to Scavenging Hyena, then playing Terrorscale Stalker on it will no longer give it +2/+1.

**Comment by troggnostupidhs** [comment]
Feign Death and Terrorscale Stalker should be tested

**Comment by troggnostupidhs** [comment]
Hunter Deck
AAEBAR8AD7MBvwHyAfsBnAK0AoUD/gPUBbkGmA3HD7ds2MIC4soCAA==

**Comment by troggnostupidhs** [comment]
Not sure if Scavenging Hyena is fixed, but Flesheating Ghoul still triggers

![img000](https://user-images.githubusercontent.com/22508641/33810837-1834db6a-ddd8-11e7-8a89-7d96ca1afec0.png)
![img001](https://user-images.githubusercontent.com/22508641/33810838-184171cc-ddd8-11e7-8923-ae75a1737f89.png)
![img002](https://user-images.githubusercontent.com/22508641/33810839-1858fd74-ddd8-11e7-8658-647c5bb182f0.png)
