### ISSUE TITLE
Shadowform is missing the 'dark fog' animation

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#420]
Shadowform used to create a dark fog animation around your hero portrait alongside changing it.
* http://us.battle.net/hearthstone/en/forum/topic/20742924967

This is how it looks currently:
* https://www.youtube.com/watch?v=uHfD69B-grE&t=5m45s

This is how it used to look in the past:
* https://www.youtube.com/watch?v=q5jGnQfwsfk&t=1m46s
* https://www.youtube.com/watch?v=60ElxgFLrOQ&t=39m29s

**Comment by Patashu** [comment]
I love that issue 420 is about a 'dark fog'

**Comment by troggnostupidhs** [comment]
https://www.youtube.com/watch?v=dOtccW0ByvQ&feature=youtu.be&t=279

I think this is fixed

**Comment by culinko** [comment]
The animation is still missing in the video you linked. Just check out the the two videos I linked at the end of my my initial post to see what I mean by the missing animation.

**Comment by troggnostupidhs** [comment]
Oh, I see it now. It's an animation on the hero portrait that happens when the card is played.

**Comment by troggnostupidhs** [comment]
Still not there.

Deck
AAEBAZ/HAgLYCscXDvsBkAKcArQC5QS5BskG0wrXCvIM7K4C+rAC8LsC0cECAA==
