### ISSUE TITLE
Shadowcaster's mana cost enchantment does not detatch on playing the copied minion

### ISSUE THREAD

**Issue by PattuX** [HearthSim/hs-bugs#502]
Similar to #468, a minion copied by Shadowcaster does not detach its mana cost enchantment, which makes Recombobulator always summon a 1-drop.
- https://youtu.be/fIlk6SHTACE

In order to solve this issue, Shadowcaster needs to seperate the stat enchantment from the mana enchantment or make the enchanment project an aura that affects the associated card like in the Miniature Warfare Tavern Brawl.

**Comment by culinko** [comment]
Fixed in 5.2.0.13619.

**Comment by Kybxd** [comment]
This is not completely fixed. Copies of 0-Cost minions (created by Shadowcaster or Sonya) still cost 1 when Sapped or Brewmastered. And they're also counted as 1-Cost when interacting with Recombobulator or Evolve. Grumble, Worldshaker doesn't have this bug.

(Starting from 10:10) https://www.bilibili.com/video/av18047000/

**Comment by culinko** [comment]
You are correct, I just re-tested this again. I played a Wisp created by Shadowcaster, then used Brewmaster/Recombobulator. In first case I got a 1 mana Wisp back to my hand and in the second case the transformed minion was a 1-drop.
