### ISSUE TITLE
Weasel Tunneler dying will stop your deck texture from updating

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#734]
If your Weasel Tunneler dies, your deck texture will stop updating until your opponent re-plays it and it gets killed again. Even adding new cards into your deck won't fix this issue. The deck texture doesn't necessarily need to be the "burning" one after hitting fatigue, if you manage to kill the Weasel Tunneler at the beginning of the game and then hit fatigue, you won't be seeing the burning texture at all. We haven't tested what happens when multiple Weasel Tunnelers die.

In this case, I went to fatigue, then my Weasel Tunneler was killed. My deck was displaying the burning texture even after playing Gang Up repeatedly and filled my deck to 60 cards.

![tunneler 1](https://cloud.githubusercontent.com/assets/11700272/25547035/bab75900-2c65-11e7-92c6-041c8391f098.png)

It was fixed after the Tunneler was re-played again and then killed:

![tunneler 2](https://cloud.githubusercontent.com/assets/11700272/25547097/f7eda086-2c65-11e7-80a7-8e08708b76ca.png)

**Comment by VoidMayonnaise** [comment]
https://youtu.be/8jzp5yfSkn8
Notice the deck, the burning effect stopped when Weasel Tunneler moved into your deck.
Seems that this is fixed, but still need some more tests.

**Comment by culinko** [comment]
I just re-tested a simple scenario (go to fatigue, kill own Weasel Tunneler, then gang up something) and the deck texture still remained burning, so the bug is still present. In your video, you haven't killed your Weasel Tunneler, but your opponent's one, that's why there was no bug.

**Comment by troggnostupidhs** [comment]
![hearthstone screenshot 09-24-17 13 19 01](https://user-images.githubusercontent.com/22508641/30784903-91791e3a-a12b-11e7-93fe-bd0c3239c8b3.png)

**Comment by troggnostupidhs** [comment]
https://youtu.be/7PAPyJ7CoYM?t=1511

**Comment by riQQ** [comment]
> Resolved an issue where Weasel Tunneller would cause a deck display issue while in Fatigue.

https://playhearthstone.com/en-us/blog/21943493/hearthstone-update-11-4-july-10-the-boomsday-project-pre-purchase
