### ISSUE TITLE
Weapon stacking bug

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#774]
There have been two reports of Sulfras 'stacking' on top of other weapons.

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20758216024

> I had a Fiery War Axe Equipped with 1 Durability left but decided to use my Sulfaras as it was better during the situation and then I realized the numbers from the old and new weapon overlapped and took screenshots but after I had finished using my Sulfaras Weapon, my 3/1 Fiery War Axe was available again however the opponent rage quit before I could see if I could use it. I have the screenshots but where can I post them?

![rjflfpq](https://user-images.githubusercontent.com/22508641/28538563-a3dd0526-707c-11e7-82f5-9eea54a5cfab.jpg)

![wxdx4fk](https://user-images.githubusercontent.com/22508641/28538567-a65e7334-707c-11e7-9f54-cc36e3b864c7.jpg)

![xtaqerr](https://user-images.githubusercontent.com/22508641/28538573-abb553ac-707c-11e7-8242-8a1267b47e34.jpg)

![qi3ch5e](https://user-images.githubusercontent.com/22508641/28538582-af32c73a-707c-11e7-9179-29ab4d412796.jpg)

![cmljpfx](https://user-images.githubusercontent.com/22508641/28538585-b43267ea-707c-11e7-9cc9-e64b9ff975a6.jpg)

![dpjdosd](https://user-images.githubusercontent.com/22508641/28538588-b709b126-707c-11e7-9eda-7e01b132655a.jpg)

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20758216034

> So.. somehow i managed to stack sulfuras on top of my 1/1 gorehowl with poison, making it so that when sulfuras is used up, i got a new 7/1 gorehowl which i could attack with.
i don't know how to recreate this bug, but photos are in links below.
(as you can faintly see, the (7) attack from gorehowl is below the (4) attack from Sulfuras.)

![lovic1n](https://user-images.githubusercontent.com/22508641/28538660-fdc7ef9c-707c-11e7-9198-35e3f9c11d4c.jpg)

![nxhfkn7](https://user-images.githubusercontent.com/22508641/28538668-05abb1a8-707d-11e7-835e-4a073b6d82a7.jpg)

![9eifryb](https://user-images.githubusercontent.com/22508641/28538672-0d2194ac-707d-11e7-9474-c5b23329b205.jpg)

![p460nmg](https://user-images.githubusercontent.com/22508641/28538677-1475bf62-707d-11e7-9730-bbd11df2b76b.jpg)

**Comment by Kybxd** [comment]
The weapon replacing bug also happened to my friend yesterday, and I also made a test. We reached the same conclusions:
1.Any weapon replacing may lead to this bug.(My friend replaced Light's Justice with Truesilver Champion, and I replace Jade Claws with Jade Claws.)
2.This is only a visual bug, for you cannot use the 'returning' weapon to attack. It seems that the 'returning' weapon appears to be at full stats because it's in the graveyard.

* http://imgur.com/a/VnEd2
Picture 1 shows that the two weapons stack. The red '1' in Durability is my new weapon, and I have attacked with it. The white '2' is my old weapon, and it's in the graveyard.
Picture 2 shows that I cannot attack with my 'returning' weapon.

* http://imgur.com/a/yE2Xb
Different weapon replacing is a real mess, but it's only a visual bug.

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/6pffvj/warrior_double_weapon_bug_pictures/

> This just randomly happened. I was able to attack with only Fools Bane and it was stuck there until I equipped another weapon.

![image](https://user-images.githubusercontent.com/22508641/28577675-71c018a4-7125-11e7-93ee-c2e3d01ee478.png)

![image](https://user-images.githubusercontent.com/22508641/28577681-76ebd75a-7125-11e7-80d8-c58ce3729629.png)

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/6pg72y/visual_bug_wicked_knife_and_obsidian_shard/

**Comment by Kybxd** [comment]
From videos in #779 we can see that this bug only happens to whoever replaces the weapon. Opponent will not see it.

**Comment by Kybxd** [comment]
This is fixed in 9.0.

**Comment by troggnostupidhs** [comment]
I think this bug is back.

Reproduction steps
1. Rapidly play several weapons. 3 or more is ideal.

Deck
AAEBAfe5AgTtBdYRuRSHxAIN+wGcArQCuQbAB9QP8RHSE7IU+aoCjrYC0bwCuM4CAA==

![image](https://user-images.githubusercontent.com/22508641/32677153-4e223340-c62b-11e7-83af-d7f583bd9af2.png)

![hearthstone screenshot 11-10-17 15 28 47](https://user-images.githubusercontent.com/22508641/32677361-1b33085a-c62c-11e7-99c3-fe388251f3b4.png)

**Comment by troggnostupidhs** [comment]
https://www.youtube.com/watch?v=8mnHi1ry6qM
