### ISSUE TITLE
Sword of Justice running out of Durability during its Play Sequence causes weird bugs

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#779]
* https://youtu.be/nWnKeuZlmkc
* https://youtu.be/CQlcMk4w8Tw
* https://youtu.be/Aw_JMZLtrS0

Video 1 and 2 show that this 'weapon' will neither lose Durability, nor be destroyed by weapon-destroying effects ,and its giving summoned minions +1/+1 effect will not activate. But Harrison will draw 5 cards and Gluttonous Ooze will gain 1 armor.
Video 3 shows that interactions with this 'weapon' will cause weird Attack Value bugs.

My friend who found this bug says this 'weapon' can be destroyed through replacing, and the new weapon will work correctly. Besides, he found this bug during testing #774, but we all agree that this bug will happen if you only play a SoJ (not replacing Ashbringer).

**Comment by Kybxd** [comment]
* https://youtu.be/n1GMN2hfTCw

If we change the Ashbringer to Truesilver, you can restore health while attacking.

**Comment by PattuX** [comment]
Lmao, thanks a lot, this is great! :D

I agree that playing SoJ without replaceing a weapon should have the same effect.

The 3rd video (Deadly Poison) might be related to #12 which is weird because that's fixed... (Or maybe it is back?) Iirc we found that there was a general issue with enchantments on entities in deck or graveyard (maybe also other zones) where they would just attatch another instance of the enchantment instead of recalculating/replacing it. This should then also tell you how many Aura Updates were running in a certain time period.

I guess playing Upgrade will result in the same bug (assuming it recognizes the SoJ as in play and does not just give you a 1/3 Hook)? If so, does this also affect durability?

Btw: With Echoing Ooze this might be one of the fastest ways to get Armor and in case Upgrade works you can draw a shitton of cards with Harrison, if you ever need to.

No clue how/why that Truesilver interaction is like that.

**Comment by Kybxd** [comment]
* https://youtu.be/WKwEAPwBD8U

Still happening, but the weapon-replacing visual bug is fixed.

**Comment by Patashu** [comment]
https://www.youtube.com/watch?v=8sTXAPI9YbY Another video of this

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/712v2m/4_bugs_persisting_after_patch_91/

https://www.youtube.com/watch?v=Oaj3fMb1Zoc

**Comment by VoidMayonnaise** [comment]
Sadly this bug is fixed. I think it was definitely the most interesting bug in hearthstone. Probably because the weapon will immediately update, rather than it used to be.
![1](https://user-images.githubusercontent.com/28046803/36793101-6f82161a-1cd7-11e8-9ce0-864064e7c8af.png)
![2](https://user-images.githubusercontent.com/28046803/36793102-706e5390-1cd7-11e8-86d7-dcfc48762a89.png)
![3](https://user-images.githubusercontent.com/28046803/36793103-71973b38-1cd7-11e8-958f-e94309259810.png)
Uther has no attack value and also he can't attack.

**Comment by Kybxd** [comment]
This bug is not completely fixed. One bug still exists: You have a Truesilver Champion, play SoJ, and it runs out of Durability during its Play Sequence. Now you have no weapon or Attack value. When you play a Light's Justice and attack with it, it will restore 2 Health for you before attack as if it were a Truesilver Champion.

If the Truesilver Champion above is changed to another weapon, its ability can also trigger, such as Ice Breaker.
