### ISSUE TITLE
Darkness Candle's timing is inconsistent with other 'Cast this when drawn's.

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#864]
When you draw a Darkness Candle, it is resolved at the timing of The Darkness rather than as a normal hand trigger.

https://youtu.be/2EHSNSaYJR0
In this video we can see that new Candles created by Dead Man's Hand still work at this timing although The Darkness has died. None of other 'Cast this when drawn's work at this timing, including Fal'dorei Strider and Deck of Wonders.

**Comment by Kybxd** [comment]
Another inconsistency: Darkness Candle's card text reads "Snuff out a candle" but it actually works in On-Play Phase. Thus it doesn't awake enemy's The Darkness when cast by Grand Archivist (you only draw a card). Other 'Cast this when drawn's are fully resolved when cast by Grand Archivist.

**Comment by troggnostupidhs** [comment]
related to #897?

**Comment by Kybxd** [comment]
Yes, but only its on-play part is fixed. On-draw part is still messed up (especially its interaction with Chromaggus).

**Comment by Jetz72** [comment]
Still happens, even with other Darknesses. Seen in the same video as #1332. Which is surprising because they've since keyworded Cast When Drawn, and also then reworked the Darkness.

Looking at the log from that, it seems to be caused by the controller enchantment ("Darkness Candle Detect" - LOOT_526et) taking responsibility for the card draw from the candle's cast when drawn. When it triggers in response to the candle, it draws the next card immediately rather than waiting for the other triggers to fire, or letting the candle draw the card itself. So subsequent triggers from the first candle have to wait until after the draw is done. 

If I had to guess what this was for, it may have be an experiment to use the trigger reentry rule to prevent infinite depth draw triggers. After the weird first draw triggers LOOT_526et and interrupts the others triggers with a second draw, all the triggers from the second draw get nested within LOOT_526et. Then when LOOT_526et itself triggers, the reentry rule delays it until afterwards, causing it to iterate safely instead of recursing to uncapped depths.

Not certain that that's the reason though, or if that's all this trigger does. Dunno why they'd need something like that for three candles of all the effects like this. Corrupted Blood could definitely benefit from a hack like this though.
